// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-RJd4vsm9h-LsTRx4QFHN_LQvoFx1iyA',
    appId: '1:893141466699:web:68cbdcbdee314f947bd7ce',
    messagingSenderId: '893141466699',
    projectId: 'fooddeliveryapp-67a45',
    authDomain: 'fooddeliveryapp-67a45.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67a45.appspot.com',
    measurementId: 'G-JQKH4NEGFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmVYqWpGCoKWIVKuPD24UkGfg8vsLM-E',
    appId: '1:893141466699:android:76ea3444455139647bd7ce',
    messagingSenderId: '893141466699',
    projectId: 'fooddeliveryapp-67a45',
    storageBucket: 'fooddeliveryapp-67a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zci24CrqT7_VYbYYYrNIovIACrGfp-E',
    appId: '1:893141466699:ios:dc6d9c973ad8701b7bd7ce',
    messagingSenderId: '893141466699',
    projectId: 'fooddeliveryapp-67a45',
    storageBucket: 'fooddeliveryapp-67a45.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zci24CrqT7_VYbYYYrNIovIACrGfp-E',
    appId: '1:893141466699:ios:dc6d9c973ad8701b7bd7ce',
    messagingSenderId: '893141466699',
    projectId: 'fooddeliveryapp-67a45',
    storageBucket: 'fooddeliveryapp-67a45.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-RJd4vsm9h-LsTRx4QFHN_LQvoFx1iyA',
    appId: '1:893141466699:web:d4be8d355481b5097bd7ce',
    messagingSenderId: '893141466699',
    projectId: 'fooddeliveryapp-67a45',
    authDomain: 'fooddeliveryapp-67a45.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67a45.appspot.com',
    measurementId: 'G-B6RYXTL950',
  );
}
